### ISSUE TITLE
Non-admin user can not change news teaser image

### ISSUE THREAD

**Issue by Balindil** [contao/news-bundle#11]
After updating Contao 4.3.x to 4.4 non-admin users can't change the news teaser image. If you click on 
source file "change selection" there is an error "Not enough permissions to access news archive ID."
![error](https://user-images.githubusercontent.com/6592711/27623482-fcee29ce-5bdc-11e7-8001-091139c5dbc2.png)
The rights for editors are set as follows:
![rights_news](https://user-images.githubusercontent.com/6592711/27623537-362e8be8-5bdd-11e7-90d7-644077c0128b.png)
Before updating everything was ok.

**Comment by fritzmg** [comment]
Probably the same issue as here: https://github.com/contao/core-bundle/issues/886

The fileTree Widget now uses the new DCA picker too.
