### ISSUE TITLE
Feature: Sortierfunktion für Nachrichtenliste

### ISSUE THREAD

**Issue by fenepedia** [contao/news-bundle#12]
Die Ausgabe der Nachrichtenliste sollte um eine Sortierfunktion ergänzt werden, so dass über das Modul gesteuert werden kann, in welcher Reihenfolge die News ausgegeben werden.

- absteigend (Datum)
- aufsteigen (Datum)
- A - Z (Titel)
- Z - A (Titel)
- Zufällig

Früher gab es eine Erweiterung news_sorted. Aus meiner Sicht eine hilfreiche Funktion die in den Core integriert werden sollte.

**Comment by speedweb** [comment]
für die aktuelle LTS...
wenn möglich nicht erst ab Version 4.4.x

**Comment by leofeyer** [comment]
Sowohl Contao 3.5 als auch 4.4 sind feature complete, daher wäre die nächste Möglichkeit für das Feature Contao 4.5.

**Comment by speedweb** [comment]
dann Bitte wenn möglich für die 4.5.x vormerken.
Es wird immer wieder nach der Möglichkeit für die unterschiedlichen Sortier Einstellungen gefragt.
Werde versuchen dies vorerst in der 3.5.x LTS selber einzubauen.

**Comment by leofeyer** [comment]
Mach doch direkt einen Pull-Request, dann können wir das übernehmen.

**Comment by fritzmg** [comment]
Den PR kann ich übernehmen (einfach die Funktionalität von news_sorted).

**Comment by speedweb** [comment]
@fritzmg: besten Dank
Habe auch schon daran gedacht. Bin aber leider für den Rest der Woche nicht im Büro.

**Comment by aschempp** [comment]
Ganz so einfach wird es wohl nicht, weil Mode 4 aktuell kein Sorting kann…

**Comment by fritzmg** [comment]
@aschempp es geht nur um die Sortierung im Frontend - also im speziellen in der Newsliste.

**Comment by leofeyer** [comment]
Siehe #13.
