### ISSUE TITLE
toggle visibility changes time field to current time

### ISSUE THREAD

**Issue by fritzmg** [contao/news-bundle#15]
### Reproduction

1. Create a news entry, set the date to an arbitrary value and the time to `01:00` for example (or anything that is not "now").
2. In the list view of the news archive, hit the toggle visibility button (green or grey eye).
3. Now go into the settings of the previously generated news entry and note it's time setting. It will be set to the current time.

![screen-shot-2017-07-18-at-13 08 30](https://user-images.githubusercontent.com/4970961/28314402-bed4abac-6bba-11e7-8a78-d9da1186a96b.png)

**Comment by leofeyer** [comment]
Fixed in aceaa6856834f5bb606379c11f821d364490f528 (and others).
