### ISSUE TITLE
Make image link to news by default

### ISSUE THREAD

**Issue by bennyborn** [contao/news-bundle#30]
Everytime we're working on a new Contao site one of the things we have to do is to adjust the listing templates to make the image link to the article.

Is there any particular reason or has this been discussed before why the image should not link to the article by default?

From an endusers perspective it's mostly expected that clicking the image would take you to the complete article.

**Comment by fritzmg** [comment]
👍 in most Contao projects we had to add something like
```php
<?php $this->arrData['href'] = $this->link; ?>
```
into the `news_latest` template.

**Comment by leofeyer** [comment]
This would conflict with the "Full-size view/new window" option, wouldn't it?

**Comment by fritzmg** [comment]
If the option _Full-size view/new window_ is set then the behavior should be that the news teaser image in `news_latest` links to the full size version of the image, as expected. If the option isn't set, the image would link to the detail page of the news entry. That's the behavior I would expect at least.

**Comment by bennyborn** [comment]
Edit: Just a second late. I'm on par with fritzmg.

Judging from my view I don't know of a single Contao project that enabled this option to make the images in the list view zoomable.

**Comment by fritzmg** [comment]
Yeah, I also have never encountered a project, where the option _Full-size view/new window_ was ever needed in news entries.

**Comment by sascha-mueller** [comment]
it should stay blank, without a link

**Comment by leofeyer** [comment]
Since everyone seems to have a strong opinion about this, let's just vote by adding a reaction (the grey smiley on the right side above this comment).

* 👍 you want the image to be linked to the news reader by default
* 👎 you want everything to remain as it is

---

Wir stimmen darüber ab, ob das Bild im Template `news_latest` standardmäßig ein Link zum Newsreader sein soll oder nicht. Über den Smiley rechts oberhalb dieses Kommentars könnt ihr abstimmen:

* 👍 ihr seid dafür, dass das Bild standardmäßig ein Link zum Newsreader wird
* 👎 ihr seid dafür, dass alles so bleibt wie es jetzt ist

**Comment by frontendschlampe** [comment]
So ... ich habe gerade mit @fritzmg im IRC kurz diskutiert und ich denke, dass die Änderung, einfach nur das Bild zu verlinken, nicht die Lösung ist, denn die Option "Großansicht/neues Fenster" muss hier auch berücksichtigt werden. Je nach Einstellung des Redakteuers (oder auch vergessen der Einstellung) kann das inkonsistente Ergebnisse nach sich ziehen. Denn mal macht er einen Haken bei Großansicht und manchmal nicht und dann ist halt manchmal ein Bild auf den Detaileintrag verlinkt und manchmal auf die Lightbox, was dann für einen Website-Benutzer zu Frust führt.

Deshalb habe ich das mal etwas umfangreicher gedacht:

1. Verlinkung auf Bild, Überschrift und "more"-Link machen
2. Die Option "Großansicht/neues Fenster" bei den Bildoptionen entfernen, denn es ist meiner Meinung nach eine globale Einstellung für das Modul
3. Die Option "Großansicht" gilt nur für die Newsdetails und sollte im Modul zum Leser eingestellt werden
4. man könnte im Modul Liste die Option einfügen, ob das Bild mit "Großansicht" belegt werden soll, dann gibt es auf dem Bild einen Link zur Lightbox (Standard wäre Link zu den Newsdetails)
5. Option "neues Fenster" gilt nur für Listenmodule und sollte beim "Weiterleitungsziel" verankert sein. Aktuell gibt es neues Fenster nur bei der Option "externe URL", aber ich könnte auch jede andere Option in einem neuen Fenster öffnen wollen

Ich will hier nicht aus der Mücke den Elefanten machen, aber wenn wir die Sachen rundherum nicht bedenken, dann bauen wir noch öfters dran herum. ;-)

Wenn man noch einstellen könnte, in welchem Format das Datum ausgegeben wird ... ;-)

**Comment by bennyborn** [comment]
@frontendschlampe Finde ich grundlegend gut, nur den letzten Satz mit dem Datum verstehe ich nicht, das kannst Du doch sowohl in den allgemeinen Einstellungen als auch im Root der Seite einstellen?

**Comment by fritzmg** [comment]
> @frontendschlampe Finde ich grundlegend gut, nur den letzten Satz mit dem Datum verstehe ich nicht, das kannst Du doch sowohl in den allgemeinen Einstellungen als auch im Root der Seite einstellen?

Beim Großteil der Websites, die wir umgesetzt hatten, musste das Datumsformat bei den Nachrichten immer anders sein, als das allgemeine Datums- und Zeitformat, das sonst wo auf der Website ausgegeben wird. Daher musst sowieso immer direkt im news Template `\Date::parse(…)` verwendet werden.

**Comment by frontendschlampe** [comment]
@bennyborn naja ... das war nur ein Zusatz, wenn man einmal daran baut. Aktuell wird immer das Feld "Datums- und Zeitformat" ausgegeben, wenn ich aber ggfs. nur das Datum, ohne Zeit haben will, dann muss ich entweder in der Seitenstruktur die Einstellung für die komplette Website ändern oder halt übers Template ran. Wenn ich aber sowieso über's Template gehen muss, dann ist die Einstellung in der Seitenstruktur auch hinfällig. Aber wie gesagt ... das nur am Rande.

**Comment by fritzmg** [comment]
Ansonsten: prinzipiell bin ich immer noch für die hier besprochene Änderung, verstehe jedoch auch die Punkte von @frontendschlampe .

**Comment by frontendschlampe** [comment]
> Der großteil der Websites, die wir umgesetzt hatten, musste das Datumsformat bei den Nachrichten immer anders sein, als das allgemeine Datums- und Zeitformat, das sonst wo auf der Website ausgegeben wird. Daher musst sowieso immer direkt im news Template \Date::parse(…) verwendet werden.

Und wenn ich direkt im Modul das Datumsformat wählen könnte, so wie in der Seitenstruktur, dann wäre das auch eine große Erleichterung. :-)

**Comment by Aybee** [comment]
@frontendschlampe Ich habe dir auch einen thumbs up gegeben, möchte aber noch folgendes hinzufügen.

Die News- und Eventtemplates sind erfahrungsgemäß die Templates, welche am meisten angepasst werden. Ist ja auch verständlich. Was wir hier jetzt versuchen zu machen ist, diverse Anpassungen direkt in die Moduleinstellungen zu bringen. Finde ich auch eine gute Idee. Dann sollte man aber auch auswählen können, was auf die Detailseite verlinkt werden soll, die Überschrift, und/oder das Bild. Morelink sowieso immer. Ich weiß nämlich nicht, ob ich dies so gut finden soll, wenn ich pro Newsvorschau drei Links auf die Detailseite habe. Ich persönlich klicke bei solchen Seiten immer alle drei Links, weil ich denke mir könnte ja was entgehen.

Man könnte natürlich auch einfach weitere Templates zur Auswahl anbieten. BTW Wäre schön, wenn die Templates dort für die Liste und den Reader mal getrennt werden. Z.B. news_list_default und news_reader_default. Sodass man die Readertemplates nicht mehr für eine Liste auswählen kann und umgekehrt.

**Comment by frontendschlampe** [comment]
@Aybee ja ... es gibt durchaus Möglichkeiten, die Optionen einzuarbeiten und ich würde es durchaus begrüßen, wenn das mit in die Einstellungen des Moduls fließen würde. Ich denke, genau das will auch die Mehrzahl der Webdesigner (also nicht Programmierer). Ich setze lieber einen Haken in einem Modul, als das Template anzupassen. Wenn man argumentiert, dass man ja das Template anpassen könne, dann brauche ich eigentlich gar keine Option mehr in irgendwelchen Elementen und Modulen, denn ich kann alles über das Template regeln! ;-) Die Abgrenzung fällt halt sehr schwer.

**Comment by skipman** [comment]
Ich halte zu viele Links auf das gleiche Ziel für verwirrend (vor allem in Hinblick auf accessibility) Letztlich müsste jeder einzelne Link einen individuellen Linktext oder Linktitel haben, um den Anforderungen der WCAG 2.0 zu entsprechen. Der Linktext bzw. Linktitel (oder die Kombination) sollten dem Besucher sagen, was passiert, wenn auf den Link geklickt wird. Wird mir "die selbe Leier" innerhalb eines kurzen Textes 3 mal  vom Screenreader vorgelesen (Überschrift, Bild, Weiterlesen), dann würde mich das sehr schnell nerven. 

Da würde mir eine Checkbox, welche die einzelne Neuigkeit als Ganzes zu **einem Link** macht wesentlich lieber. Dann hab ich entweder alles (Überschrift, Bild, Text und Weiterlesen) als einen einzigen Link, oder eben nur die _Weiterlesen_ Schaltfläche

Zusätzlich haben ja viele Startseiten nicht nur im Mainbereich einen Newsbereich, sondern auch im Footer einen Newsreader (zu den selben News...), was an sich schon für eine Verdopplung von Links sorgt.

Daher gibts von mir einen Daumen nach unten.

**Comment by fritzmg** [comment]
@Skipman die "Verdopplung" hast du ja bereits jetzt, da die Überschrift verlinkt ist und der "Weiterlesen …" link. Die ganze News verlinken kann man nur, wenn der Teaser ohne HTML Code (oder entsprechend prozessiert) ausgegeben wird, andernfalls würde es zu invalidem HTML führen, wenn der Teaser ebenfalls `<a>` tags enthält. Darüberhinaus kann es imho nicht im Sinne der Accessibility sein die Usability für reguläre User zu verschlechtern, nur um nicht mehrere Links auf das selbe Ziel zu haben.

**Comment by skipman** [comment]
@fritzmg: Als normaler User sehe ich keinen Vorteil von mehreren Links zum selben Ziel. Wenn ich mich durch eine Website durchtabbe, bin ich effektiver, wenns nur Links zu unterschiedlichen Zielen gibt. Und wenn ich die Maus benutze, tu ich mir auch nicht schwerer, weils nur _einen_ Link ínnerhalb _eines_ Newsbereichs gibt. Für mich ist das nicht nur einfacher, sondern auch übersichtlicher. Weniger ist oft mehr (als man denkt) ;-)!

**Comment by fritzmg** [comment]
Die Usability ist besser, wenn du mehr bzw. größere Clickareas hast - vor allem für Smartphone Benutzer. Ein großes Bild, das angeklickt/getippt werden kann ist schneller und einfacher zu treffen, als ein "Weiterlesen …" Link bspw..

Bzgl. tabbing: dazu kann man `tabindex="-1"` verwenden. Siehe https://www.w3.org/TR/html5/editing.html#sequential-focus-navigation-and-the-tabindex-attribute

**Comment by Aybee** [comment]
@Skipman Wie ich bereits sagte
> Ich persönlich klicke bei solchen Seiten immer alle drei Links, weil ich denke mir könnte ja was entgehen.

@fritzmg Hätte ich auf nem Smartphone drei Möglichkeiten für ein Ziel, dann hätte ich da auch wieder stark das Gefühl, "wäre es vielleicht besser gewesen, ich hätte auf einen anderen Link getappt"? Also nochmal zurück und die anderen ausprobiert. Ist jetzt natürlich von mir alles etwas überspitzt ausgedrückt.

Wollte damit nur nochmal sagen, dass ich persönlich auch kein Freund von Linkvervielfältigung bin. Deswegen wären auswählbare Optionen im Modul gut.

**Comment by fritzmg** [comment]
Wie gesagt, dieser Sachverhalt besteht ohnehin schon. Dann wäre die Diskusion eher: soll _nur_ der Weiterlesen Link existieren.

**Comment by Aybee** [comment]
Optionen im Modul diesbezüglich würden so eine Diskussion erübrigen.

**Comment by futura-web** [comment]
Normaler Weise bin ich auch immer für minimalistische Ausführungen, allerdings ist es in diesem Fall wesentlich vorteilhafter und userfreundlicher (zumal andere Systeme auch so funktionieren), wenn mind. zwei Linkoptionen (Bild + read more) implementiert werden könn(t)en. Bisher habe ich in fast einem jeden Projekt das Template anpassen müßen, aber das HTML ist in diesem Fall bescheiden. Die Überschrift als Link wird oft nicht als _clickable_ wahrgenommen (laut KlinentInnen).

**Comment by leofeyer** [comment]
Aufgrund der doch recht [eindeutigen Abstimmung](https://github.com/contao/news-bundle/issues/30#issuecomment-366164831) (39:6) habe ich die Änderungen in ba9ec2edeadc1210df3c8ce4786be9d6a554af3c implementiert.
