### ISSUE TITLE
array_intersect(): Argument #1 is not an array

### ISSUE THREAD

**Issue by qzminski** [contao/news-bundle#32]
Under some circumstances it is not possible to enter the select-multiple mode for the non-admin user. The session's current IDs tends to be not an array and thus the `array_intersect` function fails:

https://github.com/contao/news-bundle/blob/master/src/Resources/contao/dca/tl_news.php#L606

**Comment by leofeyer** [comment]
Does the error occur in Contao 4.4 or 4.5?

**Comment by qzminski** [comment]
4.4 it is, although I have not tested it under 4.5. I wonder how come this was not reported before... I suspect this issue popped out by the way introducing `SessionInterface` to handle that. On the other hand I don't even know where to start debugging it as the only place where that array seems to be set is when the multiple-select form is **submitted**: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/drivers/DC_Table.php#L153

**Comment by qzminski** [comment]
The problem could also appear in other places, e.g. https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_user.php#L542

**Comment by leofeyer** [comment]
But how can `$session['CURRENT']['IDS']` ever not be an array? We explicitly check the type in

https://github.com/contao/core-bundle/blob/14b1d0b8eeac129f1d128b82cd880852bb7f3562/src/Resources/contao/drivers/DC_Table.php#L145-L150

**Comment by qzminski** [comment]
Yeah but those line happen **after** you select the records and edit/delete/whatever them. The error however seems to pop out when this selection view is rendered, i.e. before the submit.

**Comment by leofeyer** [comment]
Can you point me at how to reproduce this please?

**Comment by qzminski** [comment]
The issue seems to appear for the users of the limited user rights so:

1. Create a news archive and some news articles as administrator.
2. Create a user group that has access to the news archive.
3. Create a user and assign it to that group.
4. Log in as that user, go to the news archive and edit multiple records.

As I said before I really wonder how this was not spot until now. Thus maybe I am missing something here but I did search for other usages of this and in other places (mostly `tl_table::checkPermission()` methods) you do first check if this session value is an array:

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_page.php#L740
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_article.php#L393

On the other hand there are other places where you don't do that:

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_content.php#L902

Thus I am bit confused why it _usually_ works elsewhere. Nevertheless it should always be checked/type-casted if this is an array before calling any function that accepts array as arguments.

**Comment by leofeyer** [comment]
I am also surprised that we did not noticed this before. Maybe PHP <7.2 gracefully ignores it? Anyway, I have added a type cast now.
