### ISSUE TITLE
Tag news and news archive in 4.6

### ISSUE THREAD

**Issue by Toflar** [contao/news-bundle#40]
Here's the page example. Should be added on both`tl_news` and `tl_news_archive`, imho.

```php
// Tag the response
if (System::getContainer()->has('fos_http_cache.http.symfony_response_tagger'))
{
    /** @var ResponseTagger $responseTagger */
    $responseTagger = System::getContainer()->get('fos_http_cache.http.symfony_response_tagger');
    $responseTagger->addTags(array('contao.db.tl_page.' . $objPage->id));
}
```

**Comment by leofeyer** [comment]
Where exactly?

**Comment by Toflar** [comment]
https://github.com/contao/news-bundle/blob/master/src/Resources/contao/modules/ModuleNews.php#L78 maybe? wdyt?

**Comment by leofeyer** [comment]
I'm not quite sure what you want to accomplish. 😄

**Comment by Toflar** [comment]
Tag any news so that you can cache the website forever in the reverse proxy and when you edit the news, this cache entry is invalidated.

**Comment by leofeyer** [comment]
But news can have several pages – one reader page and multiple list/archive pages. If a news item is changes, we would have to invalidate all of them, wouldn't we?

**Comment by Toflar** [comment]
Yes. That's why we have tags.

**Comment by leofeyer** [comment]
See #42.
