### ISSUE TITLE
Missing label for comments meta field

### ISSUE THREAD

**Issue by qzminski** [contao/news-bundle#41]
The news bundle refers to the global MSC reference as shown here:

https://github.com/contao/news-bundle/blob/master/src/Resources/contao/dca/tl_module.php#L69

And the appropriate label itself was removed in this commit:

https://github.com/contao/news-bundle/commit/bf0acf55de0820d1bee77ac9ec4f316724336567#diff-90659c84b6061a3ea0862a26db98f69f

So if there is no `contao/comments-bundle` installed, the checkbox `comments` in meta fields will not have a label:

![2018-07-18 at 09 14](https://user-images.githubusercontent.com/193483/42865788-0a9c7a2c-8a6b-11e8-94d4-7e465a7ac76a.png)

**Comment by Toflar** [comment]
Probably the right solution is not to bring the label back but to hide the "comments" option all together. Sounds like this is a feature that's only available when the comments-bundle is installed anyway?

**Comment by leofeyer** [comment]
Fixed in 1f8105a5e94d9995bde75e95ca69c0cc61ae0896.

**Comment by Toflar** [comment]
That's the wrong fix. The label must not be re-added but the option must be removed and added to the comments bundle like I wrote above?

**Comment by leofeyer** [comment]
I agree that we should optimize this in one of the next versions. However, right now – two weeks before the release – this change seems the most reasonable option to me.
