### ISSUE TITLE
Missing response tagging?

### ISSUE THREAD

**Issue by leofeyer** [contao/news-bundle#43]
@Toflar You have added response tagging once to the news bundle here:

https://github.com/contao/news-bundle/pull/42/files

However, you have added it twice to the calendar bundle here:

https://github.com/contao/calendar-bundle/pull/36/files

Is this correct? Or does the calendar bundle need a second call as well?

**Comment by Toflar** [comment]
It‘s correct. The news reader uses the same code as the list, the event reader does not ( for whatever reason).

**Comment by leofeyer** [comment]
Ok. 😊
