### ISSUE TITLE
Typo in dca/tl_news.php ?

### ISSUE THREAD

**Issue by pgerundt** [contao/news-bundle#45]
Is this a typo?
https://github.com/contao/news-bundle/blob/9dd0b57ee287d5fdccd3f1884d634e9ccbe6d59a/src/Resources/contao/dca/tl_news.php#L704

Cheers,
Pascal

**Comment by aschempp** [comment]
Do you mean the variable argument list?
https://www.php.net/manual/en/functions.arguments.php#functions.variable-arg-list.new

**Comment by pgerundt** [comment]
My bad, didn't read the whole function code properly. It's a multidimensional array. Shame on me.
