### ISSUE TITLE
news-bundle proprietary?

### ISSUE THREAD

**Issue by Aybee** [contao/news-bundle#46]
**Affected version(s)**
4.7.7

**Description**  
Hallo ich wollte das nur mal festgehalten haben. Ich war gestern in einer 4.7.7 Installation auf udmedia und dort waren alle Bundels mitinstalliert außer News. Deswegen wollte ich News nachinstallieren. Ich war sehr verwundert zu sehen, dass News dort als kostenpflichtiges Bundle ausgezeichnet war mit dem Hinweis "proprietary". Man konnte es auch nicht installieren. Der Button zum Hinzufügen enthielt einen Text ähnlich "Näheres auf der Homepage". Der Klick auf den Button führte aber wieder auf die selbe Seite auf der ich war.

Keine Ahnung, was da los war. Ne Stunde später war der Fehler dann verschwunden.

**How to reproduce**  
Can not reproduce this.

**Comment by fritzmg** [comment]
Das hat nichts mit dem news-bundle selbst zu tun, sondern ist nur ein Fehler in der Anzeige der Pakete des Contao Managers. War auch schon mal vor einiger Zeit der Fall, dass einige Pakete irrtümlich als "proprietary" angezeigt wurden.

Davon abgesehen solltest du dringend deine Contao Installation aktualisieren ;)

**Comment by Aybee** [comment]
Ups, war ein Tipfehler, habe es oben korrigiert, war 4.7.7.

Ich hatte das zum ersten Mal und wollte es nur irgendwo vermerkt haben.
