### ISSUE TITLE
Reduce multiple executions when using $this->hasText and $this->text in news_ templates

### ISSUE THREAD

**Issue by timgatzky** [contao/news-bundle#48]
The template variables are missleading compared to other variables that return a pre-evaluated value. Both variables execute a function without storing the return value for further usage. Using hasText more than once will trigger a DB-query each echo, $this->text will rebuild the whole news content every time.

Inconvenient: hasText is either boolean or executes a function. Also the naming of the variables do not make clear that a function isbeing called and stand not clear against other template variables like hasSubHeadline, hasTeaser that are clearly named and understandable in their return.

A value storage would help those functions and multiple use is not a bottle neck

**Comment by fritzmg** [comment]
Please use the mono repository for new issues and Pull Requests.
