### ISSUE TITLE
feature: exclude reader page from sitemap and forward to or display latest news

### ISSUE THREAD

**Issue by fritzmg** [contao/news-bundle#5]
By default, the reader page also gets included into the sitemap, which means search engines might index an otherwise empty page (since there is no output from the reader module when there is no parameter). People often wish to exclude it from the sitemap for that reason, or at least make it so that the reader page either forwads to or displays the latest news entry (though the latter would be duplicate content and inserting a canonical tag in such a case wouldn't make much sense imho).

So this feature request would generally be about handling empty reader pages. The reader module could provide two additional options:
- Redirect to newest entry
- Hide page from sitemap

When the first option is active, the reader module would simply search for the first news archive, that has the redirect page set to itself and generate an URL to the latest news entry from there and execute a redirect.

Furthermore, the `getSearchablePages` Hook would look for any reader modules on pages when `$blnIsSitemap` is `true` and remove the page from `$arrPages` whenever the second option of the module is set.

**Comment by Aybee** [comment]
:+1:

**Comment by leofeyer** [comment]
> By default, the reader page also gets included into the sitemap

Really? It does not on my system.

<img width="741" alt="" src="https://cloud.githubusercontent.com/assets/1192057/15924479/8a23a3b6-2e32-11e6-8f20-2897403be596.png">

Neither `event-detail.html` nor `news-detail.html` is in the list.

**Comment by aschempp** [comment]
That's a page configuration, there's a setting about sitemap ;-)

**Comment by fritzmg** [comment]
> Really? It does not on my system.

Hm, I'll have to check again.

> That's a page configuration, there's a setting about sitemap ;-)

If you remove the reader page from the sitemap, all the news entries will be remove as well (at least it used to behave that way, I didn't specifically check that in Contao 4.2).

**Comment by Aybee** [comment]
@leofeyer Many people are not able to set it up that it behaves like in your sitemap - me too. If this is possible with a setting maybe we can get an explanation on how it can be done?

**Comment by fritzmg** [comment]
@leofeyer 

> Neither event-detail.html nor news-detail.html is in the list.

`news-detail.html` **is** in the list btw. ;)

![detail](https://cloud.githubusercontent.com/assets/4970961/15926288/83105d22-2e3b-11e6-8c82-df8e40c1e9a3.png)

**Comment by leofeyer** [comment]
Hm …

**Comment by aschempp** [comment]
What's that dropdown for then?
![bildschirmfoto 2016-06-09 um 12 44 06](https://cloud.githubusercontent.com/assets/1073273/15927102/e583961e-2e3f-11e6-8762-a0cee51472b7.png)

**Comment by fritzmg** [comment]
> What's that dropdown for then?
> bildschirmfoto 2016-06-09 um 12 44 06

This removes the page from the sitemap completely. If you choose `Show never` on the news reader page fro example, it would also remove all news entries from the sitemap.

`Default` and `Show always` both also include the empty news reader page in the sitemap.

**Comment by leofeyer** [comment]
Does this issue affect Contao 3 as well?

**Comment by fritzmg** [comment]
Yes. See also
- https://community.contao.org/de/showthread.php?62601-Newsdetail-Seite-aus-der-XML-Sitemap-rausnehmen
- https://community.contao.org/de/showthread.php?62702-Nachrichten-Weiterleitungsseite-(leer)-auch-in-der-sitemap-xml

**Comment by ghost** [comment]
The issue has been moved to contao/core#8361.
