### ISSUE TITLE
Newslist is rendered as text

### ISSUE THREAD

**Issue by Systemcheck** [contao/news-bundle#50]
Hello, is there any explanation, why the newslist module is rendered as text?

All other modules  are rendered correct in 4.13.35, only this one makes some problems. 

Example output:
`<!-- TEMPLATE START: vendor/contao/news-bundle/src/Resources/contao/templates/news/news_full.html5 --> <div class="layout_full block first last even"> <h1>Test</h1> <p class="info"><time datetime="2023-12-20T17:00:00+01:00">20.12.2023 17:00</time> von Me </p> <h2>subheadline</h2> 1 </div> <!-- TEMPLATE END: vendor/contao/news-bundle/src/Resources/contao/templates/news/news_full.html5 -->`

**Comment by leofeyer** [comment]
Thank you for your contribution.

Unfortunately, you have created your issue in the wrong repository, as this is a read-only split repository. Please go to https://github.com/contao/contao and create your issue there.
