### ISSUE TITLE
RSS Teaser Image as media:content

### ISSUE THREAD

**Issue by ghost** [contao/news-bundle#7]
<a href="https://github.com/pswerbung"><img src="https://avatars.githubusercontent.com/u/1453011?v=3" align="left" width="42" height="42"></img></a> [Issue](https://github.com/contao/core/issues/8646) by @pswerbung
February 16th, 2017, 15:29 GMT

Können wir nicht das Teaser Image in zukünftigen Contao Versionen als `<media:content>` Element statt als `<enclosure>` einfügen? 

Dienste wie MailChimp könnten dann die Bilder aus dem RSS-Feed lesen und ausgeben. Das wäre wohl hier zu implementieren:
https://github.com/contao/core/blob/3.5.24/system/modules/news/classes/News.php#L209-L218

Was spricht dagegen?

**Comment by ghost** [comment]
<a href="https://github.com/fritzmg"><img src="https://avatars.githubusercontent.com/u/4970961?v=3" align="left" width="42" height="42"></img></a> Comment by @fritzmg
February 16th, 2017, 15:59 GMT

Reference regarding MailChimp: http://kb.mailchimp.com/merge-tags/rss-merge-tags

> ```
> *|RSSITEM:IMAGE|*
> ```
> 
> __Related RSS tag:__ <media:content>
>
> __What it displays:__ In [certain feed set-ups](http://www.rssboard.org/media-rss), this tag displays the image defined in the <media:content> tag. Child elements like height, width and source URL aren't editable in MailChimp, but can be included in the RSS feed on your site.

**Comment by leofeyer** [comment]
@contao/developers Any objections?

**Comment by Toflar** [comment]
Nope, as long as this complies with the standard, I'm fine with it. If it's not, it has to be fixed by MailChimp.

**Comment by aschempp** [comment]
LGTM

**Comment by leofeyer** [comment]
Implemented in 050e8c330f86cfbb9883c10df7627a0f62734ad3.
